# Generated by Django 4.1.7 on 2023-04-05 05:38

from django.db import migrations, models


def set_nickname(apps, _):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.nickname = 'user%d' % user.id
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nickname'),
    ]

    operations = [
        migrations.RunPython(set_nickname, lambda a, _: None),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=16, unique=True, verbose_name='닉네임'),
        ),
    ]
