# Generated by Django 4.1.7 on 2023-03-26 06:56

import core.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('tag', models.CharField(max_length=32, unique=True, verbose_name='태그')),
                ('zip_file', core.fields.TemporaryZipFileField(help_text='루트 폴더에 Dockerfile을 포함해야합니다', upload_to='docker_images/', validators=[django.core.validators.FileExtensionValidator(['zip'])], verbose_name='zip 파일')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
