# Generated by Django 4.1.7 on 2023-03-27 14:50

import core.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import private_storage.storage.files
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_alter_dockerimage_zip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
                ('display_name', models.CharField(max_length=32, verbose_name='보여지는 이름')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('description', tinymce.models.HTMLField()),
                ('difficulty', models.CharField(choices=[('1', 'Lv.1'), ('2', 'Lv.2'), ('3', 'Lv.3')], max_length=16, verbose_name='난이도')),
                ('test_file', core.fields.TemporaryZipFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='media/tests/', validators=[django.core.validators.FileExtensionValidator(['zip'])], verbose_name='zip 파일')),
                ('is_tested', models.BooleanField(default=False, verbose_name='테스트 여부')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='번호')),
                ('volume_tree', models.TextField(verbose_name='볼륨 트리 구조')),
                ('base_docker_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.dockerimage', verbose_name='베이스 도커 이미지')),
                ('categories', models.ManyToManyField(related_name='problems', to='problems.category', verbose_name='유형')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('path', models.CharField(max_length=255, verbose_name='경로')),
                ('contents', models.TextField(verbose_name='내용')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editable_files', to='problems.problem', verbose_name='문제')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
