# Generated by Django 4.1.7 on 2023-03-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_category_problem_editablefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editablefile',
            options={'ordering': ['name']},
        ),
    ]
