# Generated by Django 4.1.7 on 2023-04-01 03:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0004_alter_editablefile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='passed_users',
            field=models.ManyToManyField(related_name='passed_problems', to=settings.AUTH_USER_MODEL, verbose_name='통과한 유저들'),
        ),
    ]
