# Generated by Django 4.1.7 on 2023-04-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_difficulty_remove_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.difficulty', verbose_name='난이도'),
        ),
    ]
