# Generated by Django 4.1.7 on 2023-04-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='name',
            field=models.CharField(default='', max_length=16, verbose_name='이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='display_name',
            field=models.CharField(max_length=16, verbose_name='보이는 이름'),
        ),
    ]
