# Generated by Django 4.1.7 on 2023-03-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0004_submission_test_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('results_status', models.CharField(choices=[('success', '성공'), ('fail', '실패'), ('error', '에러'), ('error_timeout', '에러(시간초과)'), ('error_memory', '에러(메모리)')], max_length=32, verbose_name='결과 상태')),
                ('stderr', models.TextField(blank=True, verbose_name='에러 출력')),
                ('runtime', models.FloatField(verbose_name='실행 시간')),
                ('test_total_count', models.PositiveIntegerField(verbose_name='테스트 총 개수')),
                ('test_passed_count', models.PositiveIntegerField(verbose_name='테스트 통과 개수')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge', to='submissions.submission', verbose_name='제출')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('number', models.PositiveIntegerField(verbose_name='번호')),
                ('runtime', models.FloatField(verbose_name='실행 시간')),
                ('status', models.CharField(choices=[('success', '성공'), ('fail', '실패')], max_length=32, verbose_name='결과 상태')),
                ('queries', models.JSONField(blank=True, verbose_name='실행 쿼리')),
                ('query_count', models.PositiveIntegerField(verbose_name='쿼리 갯수')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='judge.judge', verbose_name='judge')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
