# Generated by Django 4.1.7 on 2023-03-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='runtime',
            field=models.FloatField(null=True, verbose_name='실행 시간'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='test_passed_count',
            field=models.PositiveIntegerField(null=True, verbose_name='테스트 통과 개수'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='test_total_count',
            field=models.PositiveIntegerField(null=True, verbose_name='테스트 총 개수'),
        ),
    ]
