# Generated by Django 4.1.7 on 2023-04-02 18:19

from django.db import migrations, models


def set_mean_query_count(apps, schema_editor):
    Judge = apps.get_model('judge', 'Judge')
    for judge in Judge.objects.filter(results_status='success'):
        tests = list(judge.test_results.all())
        total_query_count = sum(map(lambda t: t.query_count, tests))
        judge.average_query_count = total_query_count / len(tests)
        judge.save()


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_alter_testresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='average_query_count',
            field=models.FloatField(null=True, verbose_name='평균 쿼리 수'),
        ),
        migrations.RunPython(
            set_mean_query_count,
            lambda a, s: None,
        )
    ]
