# Generated by Django 4.1.7 on 2023-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개'),
        ),
    ]
