# Generated by Django 4.1.7 on 2023-03-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionfile',
            options={'ordering': ['name']},
        ),
    ]
