# Generated by Django 4.1.7 on 2023-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submissionfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test_status',
            field=models.CharField(choices=[('pending', '대기중'), ('in_progress', '진행중'), ('completed', '완료')], default='pending', max_length=32, verbose_name='상태'),
        ),
    ]
