# Generated by Django 4.1.7 on 2023-04-01 21:34

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='uuid',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, verbose_name='uuid'),
        ),
    ]
