# Generated by Django 4.1.7 on 2023-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submission_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='total_contents_len',
            field=models.PositiveIntegerField(null=True, verbose_name='제출 파일의 총 길이'),
        ),
    ]
