# Generated by Django 4.1.7 on 2023-04-02 18:42

from django.db import migrations, models


def set_total_contents_len(apps, _):
    Submission = apps.get_model('submissions', 'Submission')
    for submission in Submission.objects.all():
        files = submission.files.all()
        submission.total_contents_len = sum(map(
            lambda f: len(f.contents),
            files
        ))
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_submission_total_contents_len'),
    ]

    operations = [
        migrations.RunPython(set_total_contents_len, lambda a, _: None),
        migrations.AlterField(
            model_name='submission',
            name='total_contents_len',
            field=models.PositiveIntegerField(verbose_name='제출 파일의 총 길이'),
        ),
    ]
