# Generated by Django 4.1.7 on 2023-04-04 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0008_alter_submission_total_contents_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='like_users',
            field=models.ManyToManyField(related_name='like_submissions', to=settings.AUTH_USER_MODEL, verbose_name='좋아요한 유저들'),
        ),
    ]
